### ISSUE TITLE
swift 3

### ISSUE THREAD

**Issue by Tejkaran** [hoiberg/HM10-BluetoothSerial-iOS#10]
Hi - is it possible to update this for swift 3?
ignore, i realise this works for Swift 3

i wonder, is it possible to make a quick  sketch to show how to do the connect page table view? I am trying to do it, but cannot follow everything that you have done...

**Comment by hoiberg** [comment]
1. Start scanning
2. Implement bluetooth serial delegate function `serialDidDiscoverPeripheral`
3. Add every new peripheral to `peripherals` array
4. Use this array to populate the tableView.

`ConnectViewController` is no longer used btw.
