### ISSUE TITLE
C# example available

### ISSUE THREAD

**Issue by MaheshEx1990** [hoiberg/HM10-BluetoothSerial-iOS#11]
My app is built in C# code.Can i get some workound for C#.

**Comment by hoiberg** [comment]
Nope. I have no experience with C#.

**Comment by techboycr** [comment]
Technically you could... But the point is, that kinf of thing depends of the Bluetooth stack you are using in your app. Clearly you are not developing a native app so... figure out your stack understand the code that so kindly @hoiberg wrote and try it out.
