### ISSUE TITLE
New Idea

### ISSUE THREAD

**Issue by Gohstgamer** [hoiberg/HM10-BluetoothSerial-iOS#12]
Hi,

I've built a little thin g with a ble-module, but it would be much cooler if I could simply tap on some pictures to send a letter. It would be really nice if you could make a Second version of the app, where there is instand of the keyboard the possibility to place some pictures and define some letters, which will be sent when you tap on the picture.

Great Work you've done!

**Comment by hoiberg** [comment]
A **_HM10 Pro_** app is in the making! It'll cost a few bucks, but it is going to have a lot more features, including adding buttons with pre-configured actions! 
I'm trying to finish it as soon as possible, I'm expecting to get it on the App Store within a month.

**Comment by Gohstgamer** [comment]
[Zwergsignal.zip](https://github.com/hoiberg/HM10-BluetoothSerial-iOS/files/801828/Zwergsignal.zip)
Cool!
A friend of mine allready did programm my Idea in a way. But with an non paying Developper acount it's  stupid because I have to recertificate it every week.

You can be sure I'll buy your app.

**Comment by hoiberg** [comment]
It took a little longer than a month, but it's ready now!
[App Store Link](https://itunes.apple.com/us/app/hm10-bluetooth-serial-pro/id1221924372?ls=1&mt=8)

**Comment by Gohstgamer** [comment]
Hi,

Quite nice, but what I would love is, if I could chose instead of colors and text, a picture out of my camera roll for the button. Could you add such a function?

**Comment by Ferdy888** [comment]
@Gohstgamer
Omfg, are serious?? This is prototyping/debugging app.

**Comment by Ferdy888** [comment]
are you*

**Comment by hoiberg** [comment]
Well, that would I think overcomplicate the matter a bit (that's because it would need extra configuration options for size and ratio etc), plus, I think, there are not a lot of other users who'd use it.

So I don't think this feature would be worth adding. Colours and text should be enough for 99% of applications.
