### ISSUE TITLE
What should I do to connect automatically when I connect again?

### ISSUE THREAD

**Issue by cruze09** [hoiberg/HM10-BluetoothSerial-iOS#13]
When the smartphone leaves the module, the connection is disconnected.
What should I do to connect automatically when I connect again?

**Comment by hoiberg** [comment]
There are multiple ways of doing this.
If you want to reconnect to the same peripheral after the app has been shut down, you have to store the UUID of the peripheral, and use that in `centralManager didDiscoverPeripheral` to determine whether to connect to it automatically.
If you want to reconnect to a peripheral when it has lost connection, you'll only have to keep a reference to the CBPeripheral object and use `connectToPeripheral` on the centralManager.

[Apple Guideline](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/BestPracticesForInteractingWithARemotePeripheralDevice/BestPracticesForInteractingWithARemotePeripheralDevice.html)
[SO \#1](http://stackoverflow.com/questions/26878173/ios-how-to-reconnect-to-ble-device-in-background)
[SO \#2](http://stackoverflow.com/questions/13286487/how-can-i-reconnect-to-device-after-disconnecting-in-core-bluetooth)
[SO \#3](http://stackoverflow.com/questions/34290967/ble-background-reconnect)
