### ISSUE TITLE
Save and Share Buttons and Messages

### ISSUE THREAD

**Issue by LetsInspire** [hoiberg/HM10-BluetoothSerial-iOS#15]
Is there a way to share the buttons and its pre-determined messages created on one device having the Pro-App installed afterwards with other devices having the Pro-App installed or must these freshly designed on every device individually? Can I store and load different button designes and messages?

**Comment by hoiberg** [comment]
Currently, no to both questions. But import/export of buttons and storing multiple sets of buttons have already been planned as new features in future updates.
