### ISSUE TITLE
How to share the connection with several View Controllers

### ISSUE THREAD

**Issue by konsdor** [hoiberg/HM10-BluetoothSerial-iOS#17]
I would like to be able to use the Bluetooth connection with several View Controllers. How can I implement this? Now each time when switch View Controller I have to connect again.

Thanks,

Konstantin

**Comment by hoiberg** [comment]
You can do so by creating one global instance of BluetoothSerial (which is already defined in BluetoothSerial.swift) and setting its `delegate` to whichever view controller is currently using it.
For example, in ScannerViewController.swift it does so in `viewDidLoad`.

**Comment by konsdor** [comment]
Thank you! After I assigned  serial.delegate = self, I was able to share connection, but when I open View Controllers for the first time I get error "Thread 1: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value".  What should I do?

**Comment by hoiberg** [comment]
Make sure you initialise the global `serial` variable correctly before it is accessed anywhere. In this app it is done in the `viewDidLoad` of SerialViewController.swift:

    serial = BluetoothSerial(delegate: self)

But also make sure this only runs once.

**Comment by konsdor** [comment]
Thank you! It works
