### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by BurgerTsven** [hoiberg/HM10-BluetoothSerial-iOS#2]
When I am connected with the module via Bluetooth and I hit the Reset-button on my Arduino, the app crashes with fatal error. See attached screenshot.

<img width="876" alt="bildschirmfoto 2015-11-20 um 14 43 57" src="https://cloud.githubusercontent.com/assets/15943205/11301164/2cb95ad6-8f95-11e5-9d80-f6f307bb77d6.png">

**Comment by hoiberg** [comment]
I can't reproduce this issue.. Could you post the Swift code that caused the bug? (You can view the Swift code instead of the assembly code by selecting "Serial > Thread 1 > 1" in the menu bar above the console).
