### ISSUE TITLE
serial read chunks?

### ISSUE THREAD

**Issue by gritd** [hoiberg/HM10-BluetoothSerial-iOS#3]
Thank you very much for this! I was so desperately in need of Swift examples.
I've been playing around with it and have come across a 'thingy' Sorry I can't solve it myself, I still have to learn all this Swift terminology...

The thing is I replaced the 'chat' textfield with a webview field so I can easily render different colors for sender/recipient text but I noticed that serial.read() (SerialViewController, serialHandlerDidReceiveMessage() ) receives it's Bluetooth serial data in chunks (sometimes with EOF in the string)

This is a problem when I parse the string to javascript and add a <div> node to the webview.

Since I'm a beginner at Swift I tried some stuff to buffer an incoming stream until a CR is met, but my eyes still hurt looking at my code involved to attempt such a 'simple task'..

I guess for this 'chat-functionality' it would be best to store up the receiving serial data in the bottom of the DZBluetoothSerialHandler and only delegate a complete line to the serialHandlerDidReceiveMessage function if the line is complete?

**Comment by gritd** [comment]
ok well I did some changes, sorry I'm not using the full potential of github here but I don't want to ruin anything:

in DZBluetoothSerialHandler I store up the incoming characters in a buffer and check for CR:

```
    totalBuffer+=newStr
    if (totalBuffer[totalBuffer.endIndex.predecessor()]=="\u{000D}"){
    delegate!.serialHandlerDidReceiveMessage!(totalBuffer.substringWithRange(Range(start: totalBuffer.startIndex,end: totalBuffer.endIndex.advancedBy(-1))))
    totalBuffer=""
    }
```

if the CR is there I send it to the handler, stripping the CR character because webview javascript chokes in it

I change the serialHandlerDidReceiveMessage() to actually use the parsed message

```
    var msg = message;//not: org. serial.read()
    addToChat(msg,clas: "other");
```

now I have a whole line to parse to javascript

The basis of the webview is this:

```
    let htmlString:String! = "<html><head><style>body{background-color:#fff;font-family:'-apple-system','HelveticaNeue';}.me{color:#e00}.other{color:#000}</style><script>function ad(t,c){var apnd = document.createElement('div');apnd.className = c;apnd.innerHTML = t;document.getElementById('cont').appendChild(apnd);}</script></head><body><div id='cont'></div></body></html>"

    webView.loadHTMLString(htmlString, baseURL: nil)
```

and the addToChat() function does this:

```
    func addToChat(mesg:String,clas:String){
    _ = webView.stringByEvaluatingJavaScriptFromString("javascript:ad('"+mesg+"','"+clas+"');")
    }
```

I know there are more ways to make this javascript choke, best to put some kind of regex on this string but for me this is quite an achievement already.

CSS rules handle the coloring for own and other chat clients, now I just need to add the name of the connected BLE device to the 'other' chat string and all will look dandy. I hope I can figure out how to get the BLE device name string to another class...

**Comment by hoiberg** [comment]
Alright, looks like you have solved it yourself!
The only problem I see with your code is that it might 'overlook' a CR because it only checks for the last character in the received text, while there might be one in the middle (if messages are sent really fast after eachother). I'd iterate over all characters in the received text, and then split it if you find a CR.

Also, I don't really get why you would use a webview intstead of a UITextView. You can add colored text to a UITextView quite easily using its `attributedText` variable.

Lastly, what you mean by "how to get the BLE device name string to another class"?
`connectedPeripheral.name` is just an optional string like any other.

If you still have problems, I'd be happy to help. Otherwise, I'll close this issue.
Thank you for posting your code BTW, for it will serve as a reference to others :+1:

**Comment by gritd** [comment]
you may close it, I just wanted to post this addition and realise this is more a question than a code issue. I indeed better need to traverse the string instead of just checking the last character.

I was more or less lazy using the webview because HTML markup was a lot easier for me than figuring out attributedtext, I had some troubles setting the correct range for coloring and such...

thanks again for your Swift code!
