### ISSUE TITLE
New: fatal error: unexpectedly found nil while unwrapping an Optional value #3

### ISSUE THREAD

**Issue by Evoratech** [hoiberg/HM10-BluetoothSerial-iOS#5]
Hello!

I receive this error, i know why but i dont know fix it.

I receive Decimal data (Scalar) from a external machine, for example 49 ( is 1 in ascii), and your software give me the data in asci (i receive 1) and then we transform this ascii in decimal (Scalar value) because im working in Scalar values.

i use this code to transform:

extension Character
{
    func unicodeScalarCodePoint() -> UInt32
    {
        let characterString = String(self)
        let scalars = characterString.unicodeScalars

```
    return scalars[scalars.startIndex].value
}
```

}

the software works very well but the problem come when the external machine send me a number up than 128, because ascii have only 127 characters. 

I dont know how to change your software to receive scalar numbers and NO transform to ascii.

the error is in this line from DZBluetoothSerialHandler:

// there is new data for us! Update the buffer!
        let newStr = NSString(data: characteristic.value!, encoding: NSUTF8StringEncoding) as! String

¿can you help me? many thanks and sorry about my english.

**Comment by hoiberg** [comment]
You can change the code in BluetoothSerialHandler.swift where incoming data is converted to a string, to: 
`let data = characteristic.value!
         var bytes = [UInt8](count: data.length / sizeof(UInt8), repeatedValue: 0)
         data.getBytes(&bytes, length: data.length)
`

The bytes array now holds all received bytes (unsigned 8-bit integers), and you can do whatever you want with it.
If you want to send bytes to the bluetooth device, just use:
`let data = NSData(bytes: bytes, length: bytes.count)`
