### ISSUE TITLE
Feature requests.

### ISSUE THREAD

**Issue by matbor** [hoiberg/HM10-BluetoothSerial-iOS#6]
Thanks for making this app, very handy.

A few feature requests for your app;
- implement share sheet, for saving, exporting, etc
- button to pause scrolling of text automatically

This one might be out of scope for the app.
- another screen/tab that if it receives a valid NMEA string (GPS) then it displays current location on the map. Even satellite position data.

**Comment by hoiberg** [comment]
Those are good ideas, and I'll definitely add the first two in the next update. I'm currently working on other projects though, so it won't be anytime soon.

**Comment by hoiberg** [comment]
Update: I have added the first two features you requested to the Pro version, which has just been approved for sale!
[App Store Link](https://itunes.apple.com/us/app/hm10-bluetooth-serial-pro/id1221924372?ls=1&mt=8)
