### ISSUE TITLE
I want you to add some features.

### ISSUE THREAD

**Issue by menshiyun** [hoiberg/HM10-BluetoothSerial-iOS#8]
For example, allow the user to customize some of the buttons to send commands, while the location can be placed at random.
Just like Handy BLE. https://itunes.apple.com/us/app/handy-ble-simple-bluetooth/id985786496?mt=8

Thank you!

**Comment by hoiberg** [comment]
Maybe sometime in the distant future.

**Comment by hoiberg** [comment]
Update: I have added this feature to the Pro version, which has just been approved for sale!
[App Store Link](https://itunes.apple.com/us/app/hm10-bluetooth-serial-pro/id1221924372?ls=1&mt=8)
