### ISSUE TITLE
Are there any problems publishing such an app to AppStore?

### ISSUE THREAD

**Issue by georgeplaton7** [hoiberg/HM10-BluetoothSerial-iOS#9]
From what I understood working with bluetooth via serial communication requires that the device iPhone is interacting with needs to be MFI certified.

1. Did you had any such issues when you've published the app on AppStore? At review time?
2. Did the app had to be included in some special category of app?

**Comment by hoiberg** [comment]
Bluetooth 4.0 LE is excluded from the MFI program - no certification was necessary. [More Info](https://mfi.apple.com/MFiWeb/getFAQ.action#1-1).

1) Can't remember the review time, but I had to make a video demonstrating the capabilities of the app (which you usually don't have to do).
2) No.
